apiVersion: v1
kind: Pod
metadata:
  name: pod-init
spec:
  initContainers:
  - name: init-1
    image: busybox
    command: ["echo","I'm a init-container"]
  - name: init-2
    image: busybox
    command: ["sleep","30"]

  containers:
  - name: main-app
    image: busybox
    command: ["echo","Hello main container"]
  restartPolicy: Never
