apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    env: production
spec:
  containers:
    - name: nginx-container
      image: nginx
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"