apiVersion: v1
kind: Pod
metadata:
  name: nginx-4
  labels:
    app: nginx-4
    tier: frontend
spec:
  containers:
    - name: nginx-4
      image: nginx
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"