apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-rs
  labels:
    app: frontend
spec:
  replicas: 2
  template:
    metadata:
      name: nginx-pod
      labels:
        env: production
    spec:
      containers:
        - name: nginx-container
          image: nginx
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"            
  selector:
    matchLabels:
      env: production