apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
spec:
  restartPolicy: Never

  containers:

    - name: nginx-container
      image: nginx

    - name: nginx-container2
      image: busybox
      command: ["sleep","1d"]
