FROM nginx:latest
LABEL maintainer 'Aluno Cod3r <Bruno Belchior at brunovicenteb@gmail.com>'

RUN echo '<h1>Sem conteudo</h1>' > /usr/share/nginx/html/conteudo.html
COPY *.html /usr/share/nginx/html/

